rootProject.name = "ardor3d"
include(":ardor3d-savable")
include(":ardor3d-math")
include(":ardor3d-core")
include(":ardor3d-lwjgl3")
include(":ardor3d-lwjgl3-nuklear")
include(":ardor3d-lwjgl3-awt")
include(":ardor3d-lwjgl3-swt")
include(":ardor3d-swt")
include(":ardor3d-awt")
include(":ardor3d-extras")
include(":ardor3d-effects")
include(":ardor3d-collada")
include(":ardor3d-animation")
include(":ardor3d-ui")
include(":ardor3d-terrain")
include(":ardor3d-tools")
include(":ardor3d-examples")

project(":ardor3d-savable").projectDir = File("$rootDir/ardor3d-savable")
project(":ardor3d-math").projectDir = File("$rootDir/ardor3d-math")
project(":ardor3d-core").projectDir = File("$rootDir/ardor3d-core")
project(":ardor3d-lwjgl3").projectDir = File("$rootDir/ardor3d-lwjgl3")
project(":ardor3d-lwjgl3-nuklear").projectDir = File("$rootDir/ardor3d-lwjgl3-nuklear")
project(":ardor3d-lwjgl3-awt").projectDir = File("$rootDir/ardor3d-lwjgl3-awt")
project(":ardor3d-lwjgl3-swt").projectDir = File("$rootDir/ardor3d-lwjgl3-swt")
project(":ardor3d-swt").projectDir = File("$rootDir/ardor3d-swt")
project(":ardor3d-awt").projectDir = File("$rootDir/ardor3d-awt")
project(":ardor3d-extras").projectDir = File("$rootDir/ardor3d-extras")
project(":ardor3d-effects").projectDir = File("$rootDir/ardor3d-effects")
project(":ardor3d-collada").projectDir = File("$rootDir/ardor3d-collada")
project(":ardor3d-animation").projectDir = File("$rootDir/ardor3d-animation")
project(":ardor3d-ui").projectDir = File("$rootDir/ardor3d-ui")
project(":ardor3d-terrain").projectDir = File("$rootDir/ardor3d-terrain")
project(":ardor3d-tools").projectDir = File("$rootDir/ardor3d-tools")
project(":ardor3d-examples").projectDir = File("$rootDir/ardor3d-examples")
